apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: student-app
spec:
  type: NodePort
  selector:
    app: spring-boot
  ports:
    - port: 8080         # port interne
      targetPort: 8080   # port du Pod
      nodePort: 30080    # port externe fixe