apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: student-app
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdbdevops


apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: student-app
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==       # base64 de "root"
  SPRING_DATASOURCE_PASSWORD: cm9vdA==       # base64 de "root"